# Generated by Django 5.0.2 on 2024-05-16 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poster', models.ImageField(null=True, upload_to='media')),
                ('release_date', models.DateField()),
                ('enabled', models.BooleanField(default=True)),
                ('movie_status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(default='', max_length=15)),
                ('ticket_price', models.IntegerField(default=150)),
                ('total_price', models.IntegerField(default=150)),
                ('no_of_seats', models.IntegerField()),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('film_name', models.CharField(default='unknown', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieapi.event')),
            ],
        ),
    ]
